import org.apache.hadoop.yarn.proto.YarnServerNodemanagerRecoveryProtos.ContainerManagerApplicationProtoOrBuilder;
public class FunctionUse186 {
public void funcUse() {
ContainerManagerApplicationProtoOrBuilder containermanagerapplicationprotoorbuilder = new ContainerManagerApplicationProtoOrBuilder();
containermanagerapplicationprotoorbuilder.getLogAggregationContextOrBuilder();
}
}